-- Supabase SQL Editor でこのファイルの内容を実行してください。
-- (Supabaseダッシュボード → SQL Editor → New query → 貼り付けて Run)

create table if not exists public.sakes (
  id bigint generated by default as identity primary key,
  name text not null,
  prefecture text not null,
  type text not null check (type in ('pure_rice', 'ginjo', 'daiginjo', 'honjozo')),
  dry_sweet_index integer not null,
  acidity numeric,
  alcohol_percentage numeric not null,
  description text not null,
  tasting_notes text,
  food_pairing text[],
  image_url text,
  affiliate_amazon_link text,
  affiliate_rakuten_link text,
  created_at timestamptz not null default now()
);

-- 誰でも閲覧できるようにする（書き込みはSQL Editor/管理側からのみ）
alter table public.sakes enable row level security;

drop policy if exists "Public read access" on public.sakes;
create policy "Public read access" on public.sakes
  for select using (true);

-- 動作確認用の初期データ（既存の SAMPLE_SAKE_DATA と同じ内容）
insert into public.sakes
  (id, name, prefecture, type, dry_sweet_index, acidity, alcohol_percentage, description, tasting_notes, food_pairing, image_url, affiliate_amazon_link)
values
  (1, '合同酒精 鍍高譚', '北海道', 'pure_rice', -5, 1.2, 15.0, '爽やかな香りと心地よい辛口', 'さらりとした口当たり', array['刺身', '揚げ物'], '🍶', 'https://amazon.jp/'),
  (2, '国士無双', '北海道', 'ginjo', -2, 1.0, 16.0, 'バランスの取れた味わい', 'フルーティーな香り', null, '🌾', null),
  (3, '陸奥八仙', '青森県', 'ginjo', -3, 0.8, 16.0, '透明感のある辛口', null, null, '🍶', null),
  (4, '桃の里', '青森県', 'honjozo', 5, 1.5, 15.5, '甘めで飲みやすい', null, null, '🍑', null),
  (5, '月桂冠', '京都府', 'honjozo', 2, 1.3, 15.6, '伝統的な京都の味わい', null, null, '🍶', null),
  (6, '白鹿', '兵庫県', 'honjozo', -4, 1.1, 15.5, '江戸時代から続く辛口', null, null, '🍶', null)
on conflict (id) do nothing;

-- 上のidを手動指定したので、以後の自動採番がid=7から始まるよう補正
select setval(pg_get_serial_sequence('public.sakes', 'id'), coalesce((select max(id) from public.sakes), 1));
