-- Supabase SQL Editor でこのファイルの内容を実行してください。
-- (Supabaseダッシュボード → SQL Editor → New query → 貼り付けて Run)
-- /api/out/[slug]/[mall] からのアフィリエイトクリックログを記録するテーブル。

create table if not exists public.affiliate_clicks (
  id bigint generated by default as identity primary key,
  sake_id text not null,
  sake_slug text not null,
  mall text not null,
  source_flow text,
  created_at timestamptz not null default now()
);

create index if not exists affiliate_clicks_sake_slug_idx on public.affiliate_clicks (sake_slug);
create index if not exists affiliate_clicks_created_at_idx on public.affiliate_clicks (created_at);

-- 書き込み(INSERT)のみ匿名キーに許可する。閲覧はSupabaseダッシュボードまたは
-- service role キー経由の管理側集計でのみ行う想定(anon keyでの閲覧は許可しない)。
alter table public.affiliate_clicks enable row level security;

drop policy if exists "Public insert access" on public.affiliate_clicks;
create policy "Public insert access" on public.affiliate_clicks
  for insert
  with check (true);
